#!/bin/sh
# feh --no-fehbg --bg-max '/home/ni/background/background' '/home/ni/Documents/background/1576273789594.jpg' '/home/ni/Documents/background/1604107202840.png' '/home/ni/Documents/background/1577670245961.jpg' 

feh --no-fehbg --bg-scale '/home/ni/background/background' '/home/ni/Documents/background/1576273789594.jpg' '/home/ni/Documents/background/1604107202840.png' '/home/ni/Documents/background/1577670245961.jpg' 
