#!/bin/bash

ICON_DIR="$HOME/icos"
IDFILE="/tmp/vol_notify_id"

pactl set-sink-mute @DEFAULT_SINK@ toggle
status=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
vol=$(pactl get-sink-volume @DEFAULT_SINK@ | awk 'NR==1{print $5}' | tr -d '%')

if [ "$status" = "yes" ]; then
    icon="mute.svg"
else
    icon="hight.svg"
fi

prev=0
[ -f "$IDFILE" ] && prev=$(cat "$IDFILE")

body="<img src=\"$ICON_DIR/$icon\"/><br/>Nivel: ${vol}%"

newid=$(notify-send -a "" -p -r "$prev" "Volumen: ${vol}%" "$body" \
    -h string:x-canonical-private-synchronous:volume \
    -h int:value:"$vol" 2>/dev/null)

[ -n "$newid" ] && echo "$newid" > "$IDFILE"
