# ACA EL BUILD QUE SE EJECUTARA PARA DEFINIR USERS Y DEMAS CONFIGURACIONES 
# LUEGO SE CREA UNA IMAGEN CON TODO LO INSTALADO ACA Y SE 
# CONSIGUE UNA IMAGEN CON LAS CONFIGS INMUTABLES Y USERS 
# ADEMAS LAS APPS QUEDAN PERSISTENTES Y LA CONFIG QUEDA EN LA FOLDER DEFINIDA DEL HOST

