version: "3.8"
services:
  appen:
    image: archlinux
    container_name: appen
    command: sleep infinity
    cpus: 3
    mem_limit: 6g
    network_mode: bridge
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges
    volumes:
      - ~/appendata:/home/a:rw,z
