#!/bin/sh
xsetwacom --list devices
xsetwacom set "Wacom Intuos S Pen stylus" Area 4300 0 12000 7500
xsetwacom --set "Wacom Intuos S Pen stylus" Button 2 "pan"
xsetwacom --set "Wacom Intuos S Pen stylus" PanScrollThreshold 200
#xsetwacom --set "Wacom Intuos S Pen stylus" Button 3 "button +3"
#xsetwacom --set "Wacom Intuos S Pad pad" Button 1 "key ctrl c"
#xsetwacom --set "Wacom Intuos S Pad pad" Button 2 "key ctrl v"
#xsetwacom --set "Wacom Intuos S Pad pad" Button 3 "key +Shift_L ; -Shift_L x Return"
#xsetwacom --set "Wacom Intuos S Pad pad" Button 8 "key v space +ctrl +shift v -ctrl -shift Return"

xsetwacom --set "Wacom Intuos S Pen stylus" Button 3 "key . Return"
xsetwacom --set "Wacom Intuos S Pad pad" Button 3 "key g g 9 9 d d"
xsetwacom --set "Wacom Intuos S Pad pad" Button 8 "key ctrl v"
xsetwacom --set "Wacom Intuos S Pad pad" Button 2 "key +Shift_L ; -Shift_L x Return"
xsetwacom --set "Wacom Intuos S Pad pad" Button 1 "key v space +ctrl +shift v -ctrl -shift Return"
xsetwacom --set "Wacom Intuos S Pad pad" Button 8 "key ctrl c"
